// Add new employee

export const GET_CHAPTER_QUESTION_REQUEST = 'GET_CHAPTER_QUESTION_REQUEST'
export const GET_CHAPTER_QUESTION_SUCCESS ='GET_CHAPTER_QUESTION_SUCCESS'
export const GET_CHAPTER_QUESTION_FAILED ='GET_CHAPTER_QUESTION_FAILED'